ios ISO15693 extended read/write commands (0x30 and 0x31)
nfcim/flutter_nfc_kit pull request #117
Opened 2023-10-04 16:03 UTC by engeen

ios ISO15693 extended read/write commands (0x30 and 0x31)
ios 13.0 only available

2023-10-05 14:03 UTC, jiegec requested changes

2023-10-05 14:03 UTC, jiegec commented on ios/Classes/SwiftFlutterNfcKitPlugin.swift
> +@available(iOS 13.0, *)
Please reformat the code

2023-10-05 14:03 UTC, jiegec commented on ios/Classes/SwiftFlutterNfcKitPlugin.swift
> +  @available(iOS 13.0, *)
What will happen if it is not available?

2023-10-05 14:03 UTC, jiegec commented on ios/Classes/SwiftFlutterNfcKitPlugin.swift
> +        }
What if tag is not iso15693?

2023-10-05 14:03 UTC, jiegec commented on lib/flutter_nfc_kit.dart
> +  ///
If you want to format code, please move these changes to a separate pull request.

2023-10-29 14:23 UTC, Harry-Chen commented
@engeen Would you mind refining your code according to the reviewer's comments? Then I will be happy to merge your code.

2023-10-29 16:19 UTC, engeen commented
Hi, Shegqi. Yeah, There were really good comments and I hope I will find a
time to make a good contribution. But theres a lot of work, so still on
hold.

Вс, 29 окт. 2023 г. в 22:23, Shengqi Chen ***@***.***>:

> @engeen <https://github.com/engeen> Would you mind refining your code
> according to the reviewer's comments? Then I will be happy to merge your
> code.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nfcim/flutter_nfc_kit/pull/117#issuecomment-1784128206>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAFYWXI23L6QCOXYPRCTTLYBZRF7AVCNFSM6AAAAAA5S33AW6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOBUGEZDQMRQGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-10-30 12:45 UTC, Harry-Chen approved these changes
LGTM

2023-10-30 12:48 UTC, merged